apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-report-cronjob
spec:
  schedule: "0 2 * * *"  # Every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-report
              image: 180294184800.dkr.ecr.ap-south-1.amazonaws.com/kce/aggregator-service:v0.0.1
              env:
                - name: DB_HOST
                  value: "ls-1da58d02ca2520ec50e600aa762e63871c25220d.c5g2628m27rg.ap-south-1.rds.amazonaws.com"
                - name: PG_DB
                  value: "moon-agent"
                - name: PG_USER
                  value: "moonagentuser"
                - name: PG_PASSWORD
                  value: "DWIJRwybuh038&$"
          restartPolicy: OnFailure
