name: Build and Deploy to EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: kce-dev
  ECR_REGISTRY: 180294184800.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    - name: Deploy to EKS
      run: |
        kubectl apply -f agent-service/deployment.yaml
        kubectl apply -f agent-service/service.yaml
        kubectl apply -f aggregator-service/aggregator-cron.yaml
        kubectl apply -f integration-service/deployment.yaml
        kubectl apply -f integration-service/service.yaml
        kubectl apply -f notification-service/deployment.yaml
        kubectl apply -f notification-service/service.yaml
        kubectl apply -f redshift-publisher-service/sync-redshift-cronjob.yaml
